### ISSUE TITLE
Add a version

### ISSUE THREAD

**Issue by xavier-GitHub76** [C4illin/ConvertX#10]
Hello,

I install convertx with docker (version : main).
Thanks for your work.
You have 2 branch (main and master) and no tag.

Could you add a version ?

Best regards

**Comment by C4illin** [comment]
Yes I could try to do that. Why do you want it?

**Comment by xavier-GitHub76** [comment]
THANKS
 It is a good practice to version for:
- monitoring of anomalies/corrections
- monitoring migrations between versions.
I found a bug, I wanted to create a report on Github and give you the version concerned

**Comment by C4illin** [comment]
I am convinced and will know use versions. Thanks for the suggestion!
