### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by otonoton** [C4illin/ConvertX#110]
Can a screenshot be added somewhere like the README or on a website linked from there? I'm interested in using this program but I want to see what it looks like first before I try to install it.

Also is there a list of all the supported file formats somewhere?

**Comment by aobxc** [comment]
Hello,

I installed it. Here is a screenshot:

![image](https://github.com/user-attachments/assets/36f5d2ec-9928-4f08-8dd4-5ce6a6f990b3)

![image](https://github.com/user-attachments/assets/e5f3e150-7593-4222-b79d-fe7101670ed3)

**Comment by C4illin** [comment]
There is /conversions if you install it. It displays for all available conversions, but it isn't that great. Probably better to look in the docs of the actual converter to see the available conversions
