### ISSUE TITLE
Feature: Unauthenticated file conversions

### ISSUE THREAD

**Issue by luis-c465** [C4illin/ConvertX#114]
Would be great if there was an environment variable to allow users to convert files with ought having to sign in first. Is this possible or safe with how the app is currently built?

**Comment by C4illin** [comment]
Is it ok if The unauthorized user can see all conversions? That would be quite easy to do

**Comment by 101br03k** [comment]
for me this would be fine since everything in my stack is only local accessibel.

**Comment by egodigitus** [comment]
Would be in favor of this feature as well.
I would suggest to remove the history "feature" completely for unauthenticated users.

**Comment by C4illin** [comment]
Now it works by generating a random user id above the normal user ids and then signing a jwt with it. Creating a temporary guest user, so all features should still work

**Comment by luis-c465** [comment]
Tested in Docker and looks like conversion and file history work even when not signed in :)

As expected, I could not get other unauthenticated users to views the converted images even when knowing the URL of the image.
