### ISSUE TITLE
Cant't logout

### ISSUE THREAD

**Issue by xavier-GitHub76** [C4illin/ConvertX#12]
Hello

I install ConvertX with docker with image main.
The image have no tag, I use inspect to give you informations about precise version : 
![image](https://github.com/C4illin/ConvertX/assets/82046143/14a751bf-42bc-4a45-9884-09e1377eee3d)

I succed to login but I can't logout
https://github.com/C4illin/ConvertX/assets/82046143/a202e15b-f883-41e6-b667-6a4b82877cd3

Best regards

**Comment by C4illin** [comment]
Do you get 301: moved permanently if you check network when pressing logout?

**Comment by xavier-GitHub76** [comment]
Yes :
[image: image.png]


Le jeu. 30 mai 2024 à 13:19, Emrik Östling ***@***.***> a
écrit :

**Comment by C4illin** [comment]
Does it work with the new image?

**Comment by xavier-GitHub76** [comment]
Thanks for your reactivity

It's OK 👍

Le ven. 31 mai 2024 à 01:54, Emrik Östling ***@***.***> a
écrit :
