### ISSUE TITLE
unable to login after first account creation

### ISSUE THREAD

**Issue by tomshomelab** [C4illin/ConvertX#122]
docker compose

i create an account on first login however the screen refreshes to allow me to login with my new account and when i enter my details im not logged in. 

no errors from the container. 

i can bypass the login by settings `ALLOW_UNAUTHENTICATED=false` to `true`

**Comment by C4illin** [comment]
is it over https?

**Comment by PhuriousGeorge** [comment]
Same issue here.  Setup the admin account appears to work (no confirmation) but attempting to login with http only just cycles the login page (no error dispalyed).  I also have ALLOW_UNAUTHENTICATED set to true, but see no way of bypassing the (apparent) failed login.

**Comment by C4illin** [comment]
Is HTTP_ALLOWED=true?

**Comment by PhuriousGeorge** [comment]
Yes

**Comment by C4illin** [comment]
Could you send your docker compose file?

**Comment by PhuriousGeorge** [comment]
I don't use compose, so I styled the Unraid template based on the compose example.  Here's a docker run export:

`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='ConvertX' --net='bridge' --pids-limit 2048 -e TZ="America/Chicago" -e HOST_OS="Unraid" -e HOST_HOSTNAME="PGHYDRA" -e HOST_CONTAINERNAME="ConvertX" -e 'ACCOUNT_REGISTRATION'='False' -e 'HTTP_ALLOWED'='True' -e 'ALLOW_UNAUTHENTICATED'='True' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:3000]' -p '3020:3000/tcp' -v '/mnt/user/appdata/convertx':'/app/data':'rw' 'ghcr.io/c4illin/convertx'`

**Comment by C4illin** [comment]
It should be "true" and "false" without any capital letters.

**Comment by C4illin** [comment]
could you test the :latest image to see if it works now?

**Comment by PhuriousGeorge** [comment]
Doesn't appear that 0.4.1 is released quite yet, but I did correct my template to lowercase-only (I feel dumb now) and it works as intended, cheers!

**Comment by C4illin** [comment]
> Doesn't appear that 0.4.1 is released quite yet, but I did correct my template to lowercase-only (I feel dumb now) and it works as intended, cheers!

Oh sorry I meant the dev image :main. Great that it works!
