### ISSUE TITLE
 [Converter] 3D Mesh conversion

### ISSUE THREAD

**Issue by jo-chemla** [C4illin/ConvertX#144]
It might be useful for 3D-artists and professionals working with 3d-data to use ConvertX - or a selfhosted instance - to convert between 3D mesh formats - like gltf, usd, fbx, abc, obj, ply etc. Multiple libraries exists like [Open3D](https://www.open3d.org/docs/release/python_example/io/index.html#triangle-mesh-io-py) with python bindings, or [PyMeshLab](https://github.com/cnr-isti-vclab/PyMeshLab) - a CLI does exist for standard non-pythonic meshlab.

**Comment by jo-chemla** [comment]
Yes that's a great deal of 3d file formats supported by using assimp, thanks for sharing that new PR! 

Some notable missing ones:
 - usd or usdz which seem to be supported by assimp
 - abc which is not yet supported by assimp

**Comment by jo-chemla** [comment]
Thanks for the new release with 3d-support via assimp!

**Comment by C4illin** [comment]
Yeah thanks @Aymendje !
