### ISSUE TITLE
Logging in does nothing

### ISSUE THREAD

**Issue by pickles4evaaaa** [C4illin/ConvertX#145]
I can pull up the login screen. I enter my credentials, press login, then the page just goes back to the login screen. I have tried this on Safari and Chrome. 

This is the command I used to run:

**docker run -p 3069:3000 -v ./data:/app/data ghcr.io/c4illin/convertx**

![Screenshot 2024-09-25 at 14 16 17](https://github.com/user-attachments/assets/bea72129-cc67-4526-a291-ce41688cb15b)

**Comment by C4illin** [comment]
Set -e HTTP_ALLOWED=true IF you access it over http

**Comment by C4illin** [comment]
Should probably add a warning to the welcome screen

**Comment by pickles4evaaaa** [comment]
Thanks, so I ended up just redoing the docker-compose. It looks like I did not set the volume correctly the first time. Thanks for your help! It is working now.

**Comment by C4illin** [comment]
Great that you got it to work!
