### ISSUE TITLE
bug: no autocomplete

### ISSUE THREAD

**Issue by cachho** [C4illin/ConvertX#150]
docker-compose, `0.6.0`

**Comment by cachho** [comment]
![image](https://github.com/user-attachments/assets/8eece9bf-fb40-4d4a-b6d7-de4ed926a0e9)

**Comment by C4illin** [comment]
No popup at all? What does the web console say?

**Comment by cachho** [comment]
![image](https://github.com/user-attachments/assets/50df8254-fa50-4792-b328-58f04edd67c5)

**Comment by cachho** [comment]
it takes a while for this to pop up.

**Comment by C4illin** [comment]
Seems like the server is very slow to respond. Are you running it on a low power system or over a slow network?

**Comment by cachho** [comment]
yes I guess that was a problem with my server

**Comment by C4illin** [comment]
Still weird that it misbehaves like that. It should definitely be able to display the ui correctly. What system are you running?

**Comment by cachho** [comment]
> Still weird that it misbehaves like that. It should definitely be able to display the ui correctly. What system are you running?

Chrome on Windows 10 and the website is hosted via docker-compose on Debian.
