### ISSUE TITLE
bug: console log `{message: 'Files uploaded successfully.'}` comes in noticably after it appears in the frontend

### ISSUE THREAD

**Issue by cachho** [C4illin/ConvertX#152]
I'm assuming that the console is right. Maybe there should be a frontend cue to signal that the upload was completed.

![image](https://github.com/user-attachments/assets/c5cb1fac-467e-4252-896d-40fc1868c036)

**Comment by C4illin** [comment]
should add a progressbar for the upload, the console.log is when everything is done
