### ISSUE TITLE
not support .awb to  .mp3

### ISSUE THREAD

**Issue by xw-l** [C4illin/ConvertX#153]
In fact, the .awb format is supported by ffmpeg

**Comment by C4illin** [comment]
Is it only for input?

**Comment by xw-l** [comment]
of course can output
![e6661cb4-9c6d-4d2f-a663-fe5bf88bf741](https://github.com/user-attachments/assets/7a6259f4-8b11-4244-a45a-82930fcfaad3)

**Comment by C4illin** [comment]
sorry I mean can you do `ffmpeg -i example.mps out.awb`

**Comment by xw-l** [comment]
can‘t

**Comment by C4illin** [comment]
nice then everything should be correct in #154

**Comment by xw-l** [comment]
ok,thanks,Good tools！！！
