### ISSUE TITLE
Possible .jfif file format support?

### ISSUE THREAD

**Issue by Bluecolty** [C4illin/ConvertX#163]
Hey, just started running ConvertX on my unraid machine and it works great! This is such a wonderful container you've made, it just _works_.

I know you've got a ton of stuff on your TODO list, but if you have the time, support for the .jfif format would be really awesome. It's a somewhat common format when you download images from the web. Being able to quickly upload and convert a .jfif image to something else would be wonderful.

I just tried it a few minutes ago and it uploads fine, but when I search for conversions, none appear. It looks like its a matter of just changing the file extension from .jfif to .jpg

Let me know if you need anything else from me, this is my first time opening an issue on GitHub.

**Comment by C4illin** [comment]
None of the available converters seem to make correct jfif images.

Vips is the only one that supports jfif out of the box, but it seems to be a "fake" format https://github.com/libvips/libvips/issues/3775

So either I treat it as a jpeg or allow vips to read and save fake jfif images. I think I prefer the vips approach since jpeg isn't fully jfif if I understand everything correctly.

**Comment by Bluecolty** [comment]
Oh just to clarify so we're on the same page, this is for converting a .jfif image to something else, such as a jpeg.

So maybe, just treating it as a jpeg would be an option? It reads a .jfif as a jpeg, tells the various converters its a .jpeg, then gives the options to convert it to something else. Maybe that could be an implementation with vips so it can read the file and then convert accordingly.

**Comment by C4illin** [comment]
Well I mean that jfif is an extension to the jpeg standard, which isn't supported. But if you treat it like an jpeg it is supported, which vips by default does, but not the other programs.

**Comment by Aymendje** [comment]
jfif is just a subset of compressed jpeg, and should be supported by any converter.
It is usually safe to rename "jfif" to "jpeg" (see https://superuser.com/questions/1657480/is-it-safe-to-simply-rename-a-jfif-file-to-jpg)

We could simply add ".jfif" to any of the ".jpeg" converters (I tried on ffmpeg and imageMagick and it works without any issues)

**Comment by C4illin** [comment]
Yeah probably makes more sense to just treat it as a jpeg then

**Comment by Bluecolty** [comment]
Thanks so much for adding it! Apologies for not responding sooner, I missed the email notification. I really appreciate you taking the time to look at it.

**Comment by C4illin** [comment]
No worries, thanks for reporting it!
