### ISSUE TITLE
Trying to convert heic to jpeg - failed, check logs error

### ISSUE THREAD

**Issue by chaosclarity84** [C4illin/ConvertX#168]
This is a fresh deployment on unraid, nothing special. I converted a small handful of files just fine the other day.. but now when I try it just flat out says "Failed, check logs".

The logs show this:

` 7 |       throw err.code = "ERR_INVALID_ARG_TYPE", err;
 8 |     }
 9 |   }
10 |   var setup = () => {
11 |     const { FixedQueue } = @getInternalField(@internalModuleRegistry, 10) || @createInternalModuleById(10);
- |     function processTicksAndRejections() {
ENOENT: No such file or directory
   errno: -2
 syscall: "open"
   path: "./data/output/1/10/IMG_8644.jpg"`

**Comment by C4illin** [comment]
Something went wrong when the files were uploaded. Maybe you were to fast or the job id didn't update corectly. 

Jpg -> heic and heic -> jpg is no problem

**Comment by C4illin** [comment]
related to #152
