### ISSUE TITLE
ConnvertX let me Start Conversion Job without Upload be finished.

### ISSUE THREAD

**Issue by virtualized-human** [C4illin/ConvertX#177]
Hello,

I have encountered the very annoying problem that ConvertX apparently does not show me the upload status. That's not the big problem, the bigger one is that it looks to the user as if he can already convert immediately. If you start a job without a complete upload, it will logically fail.

Is this an error by design and intentional or is it unintentional?
![grafik](https://github.com/user-attachments/assets/0f1d03d4-712b-4bf7-b571-ab0729a6ece7)
meanwhile:
![grafik](https://github.com/user-attachments/assets/3f19cc6a-0740-43e3-8014-b6817d7aeb55)
if i now start conversion, it logically fails:
![grafik](https://github.com/user-attachments/assets/1c608777-2b00-4c81-b17c-885be56d5c90)

Have a nice day!

**Comment by C4illin** [comment]
This is a priority to add. I am busy with exams but will look at it soon.

**Comment by C4illin** [comment]
Related to #152

**Comment by C4illin** [comment]
Added a simple disable when the file is uploading, what do you think?

**Comment by virtualized-human** [comment]
jobId set to: 3
stderr: ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
./data/uploads/1/3/2024-10-11 18-39-06.mp4: No such file or directory

Failed to convert ./data/uploads/1/3/2024-10-11 18-39-06.mp4 from mp4 to mov using ffmpeg. error: Error: Command failed: ffmpeg -i "./data/uploads/1/3/2024-10-11 18-39-06.mp4"  "./data/output/1/3/2024-10-11 18-39-06.mov"
ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
./data/uploads/1/3/2024-10-11 18-39-06.mp4: No such file or directory


for me its like bevore. it does not indicate that upload is still processing. with the branch you made there.

**Comment by virtualized-human** [comment]
![grafik](https://github.com/user-attachments/assets/4a460a6a-a3f4-47fd-b926-17a18dcf717a)

**Comment by virtualized-human** [comment]
ah fuck my bad :D

**Comment by virtualized-human** [comment]
so the button stays invisible yes until uploaded, but only if you dont select a convert to meanwhile :). if you select a format to convert to while uploading the button would be instantly useable. so its not really good implementation.

**Comment by virtualized-human** [comment]
@C4illin so the button remains invisible yes, until uploaded, but only if you don't choose a conversion in the meantime :). if you choose a format to convert while uploading the button would be immediately usable. so its not really good implementation.

**Comment by C4illin** [comment]
Ohhhh didnt think of that, will fix!

**Comment by C4illin** [comment]
this should fix it
