### ISSUE TITLE
add whatsapp audio formats to convert to mp3

### ISSUE THREAD

**Issue by akamuraaa** [C4illin/ConvertX#178]
i noticed that whatsapp gives me several different formats by downloading audio files, but i want to convert them to mp3.
so far i saw .dat.unknown and .whaptt.opus

**Comment by C4illin** [comment]
What format is it more specifically?

**Comment by akamuraaa** [comment]
This a file created by the Android MediaRecorder. Header contains ftypmp42 isommp42.
I don't know what this means, but i hope it's helpful.

**Comment by akamuraaa** [comment]
Also i notice .whaptt.opus works already

**Comment by C4illin** [comment]
Do you have a sample file for .dat.unknown?

**Comment by akamuraaa** [comment]
yes, i can't upload it here, so i have to use wetransfer.
https://we.tl/t-8pVwEK9xl4

**Comment by C4illin** [comment]
This seems to be a aac file. I can add so that it detects it as aac, but it will make all .unknown detect as aac, what do you think?

**Comment by akamuraaa** [comment]
if this works, of course.
maybe whatsapp uses this .dat.unknown to compress files. my phone records in .m4a files. so this should work for all .dat.unknown files from whatsapp.
