### ISSUE TITLE
Convert button takes me back to log in screen

### ISSUE THREAD

**Issue by 60beetle60** [C4illin/ConvertX#179]
Hi, 
I've just tried deploying this with docker compose, I've created my account but I can't get anything to convert. I upload a file, select my conversion type from the options, but when I hit the convert button I get taken back to the log in page. 
I've tried changing both HTTP_ALLOWED and ALLOW_UNAUTHENTICATED to be true but it doesnt make any difference. 

Looking for suggestions on how to resolve

Compose compose is below if required. 

services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment: # Defaults are listed below. All are optional.
      - ACCOUNT_REGISTRATION=false # true or false, doesn't matter for the first account (e.g. keep this to false if you only want one account)
      - JWT_SECRET=aLongAndSecretStringUsedToSignTheJSONWebToken1234 # will use randomUUID() by default
      - HTTP_ALLOWED=false # setting this to true is unsafe, only set this to true locally
      - ALLOW_UNAUTHENTICATED=false # allows anyone to use the service without logging in, only set this to true locally
      - AUTO_DELETE_EVERY_N_HOURS=24 # checks every n hours for files older then n hours and deletes them, set to 0 to disable
      - TZ=Australia/Adelaide      
    volumes:
      - /mnt/nvme/docker/data/convertx:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.convertx.rule=Host(`convertx.redacted.com`)
      - traefik.http.routers.convertx.entrypoints=https
      - traefik.http.routers.convertx.tls=true
      - traefik.http.services.convertx.loadbalancer.server.port=3000
networks:
  traefik_proxy:
    external: true

**Comment by veesiom** [comment]
+1
Can't even get it to work once. Doesn't matter it's in compose or not.

Also: if i use ALLOW_UNAUTHENTICATED=false i simply stuck with the login page. I register and i can't login anymore :)
If i use ALLOW_UNAUTHENTICATED=true — i register, i can login... and it's pretty much it. I can see the conversion page, but clicking on convert or history gets me back to login page.
Tried main / latest versions, no difference. 
@C4illin any idea what's causing it and how to get it work?

I would like it to be possible using these vars make it fully opened without using any form of "accounts / login pages" if i'm planning to use it within my private networks.

**Comment by C4illin** [comment]
Very weird error, could you guys test the `ghcr.io/c4illin/convertx:main` image?

> I would like it to be possible using these vars make it fully opened without using any form of "accounts / login pages" if i'm planning to use it within my private networks.

ALLOW_UNAUTHENTICATED=true should be almost like this, the login page should not be shown unless you press login

**Comment by veesiom** [comment]
As i've said above i've tried both main and latest images.
What's exactly the way of getting the logs?
Usually, running Docker, i get logs through `docker logs <container>` command, but in this case it's only output is kinda tech info like this:
```
[ansible@localhost ~]$ sudo docker ps | grep convertx
95ec661e4e06   ghcr.io/c4illin/convertx   "bun run ./src/index…"   4 minutes ago   Up 4 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   convertx
[ansible@localhost ~]$ sudo docker logs convertx
ConvertX v0.8.1
🦊 Elysia is running at http://localhost:3000
Alpine Linux v3.18
GraphicsMagick 1.3.40 2023-01-14 Q16 http://www.GraphicsMagick.org/
XeTeX 3.141592653-2.6-0.999995 (TeX Live 2023/Alpine Linux)
resvg v0.43.0
djxl v0.8.2 [AVX3,AVX2,SSE4,SSSE3,SSE2]
assimp vVersion 5.2 -shared -st (GIT commit 0)
Bun v1.1.29
pandoc 3.1.2
ffmpeg version 6.0.1 Copyright (c) 2000-2023 the FFmpeg developers
vips-8.14.3
jobId set to: 1
jobId set to: 2
jobId set to: 3
jobId set to: 4
```

I also tried using it without compose, but couldn't figured out if i'm able to specify these extra parameters.
Here's a quick video of a fresh installed app with ALLOW_UNAUTHENTICATED=true and ACCOUNT_REGISTRATION=false
behavior.

https://github.com/user-attachments/assets/b402f151-3347-4c02-8ffc-e245f3abd1a5

**Comment by C4illin** [comment]
Thanks for the video looks super weird, my guess is that something is weird with cookies. Could you press F12 in the browser and look at the web browser console (maybe some other button on mac), and do the same thing?

> As i've said above i've tried both main and latest images.
Sorry missed that :(

**Comment by veesiom** [comment]
I see only these until i press convert. 
<img width="641" alt="image" src="https://github.com/user-attachments/assets/db532297-f70b-4618-96c5-d1ab7868f660">
Sorry, i couldn't find a way to display it in english. It basically says:
- "cookie <auth> was refused since non-HTTPS-cookie cannot be set as <secure>" (same for jobId cookie)
And when i press convert button it just flushes and i'm facing login screen again

**Comment by C4illin** [comment]
Then `HTTP_ALLOWED=true` should fix it

**Comment by veesiom** [comment]
> Then `HTTP_ALLOWED=true` should fix it

Bruh. it really did...

If i get SSL cert installed would it get rid of these errors? Can't do it atm, so just asking.

**Comment by C4illin** [comment]
> Bruh. it really did...

Great! 

> If i get SSL cert installed would it get rid of these errors? Can't do it atm, so just asking.

Yes, the reason for the errors is that the cookie is set to https only by default. 

> UPD: sorry for the late response, been hella-busy that week

No worries!
