### ISSUE TITLE
SQLiteError: unable to open database file

### ISSUE THREAD

**Issue by zarevskaya** [C4illin/ConvertX#8]
Hello, first thing, thanks for your work!

I'm using the docker-compose in your main page, Debian 12 and Docker V2.

Just installed now and I have this issue:

18 | import {
19 |   normalizeFiletype,
20 |   normalizeOutputFiletype,
21 | } from "./helpers/normalizeFiletype";
22 | 
23 | const db = new Database("./data/mydb.sqlite", { create: true });
                ^
SQLiteError: unable to open database file
 errno: 14
  code: "SQLITE_CANTOPEN"
      at new Database (bun:sqlite:160:27)
      at /app/src/index.tsx:23:12
Bun v1.1.10 (Linux x64 baseline)
The only way what I found it's to do that:

sudo chown 1000:1000 data/ -R
It's a good way?

**Comment by C4illin** [comment]
Yes chown is what I did as well, I think you don't need recursive but it doesn't hurt. I will check if it can be done in the dockerfile in some way

**Comment by zarevskaya** [comment]
Thanks for the answer! I wrote an article/tutorial) in french about your app.
It's promising.

**Comment by C4illin** [comment]
Wow thank you! How did you find this app?

**Comment by zarevskaya** [comment]
Good question Monsieur,

I go to this page: 

https://github.com/topics/self-hosted

I sort by "recently updated" and I try to find the rare gem that will serve as the basis for an article.
Today was a good day, I found your work! 

If you want to show your app, come back to my site at midnight.

https://belginux.com

Have a nice day!

**Comment by zarevskaya** [comment]
https://belginux.com/installer-convertx-avec-docker/
Done ;)

**Comment by C4illin** [comment]
Very nice! Just so you know the first account can be created even if registration is disabled, I should probably clarify that:) I will add the link to the readme

**Comment by C4illin** [comment]
Will close this issue since it doen't seem fixable unfortunately, or at least I didn't find anything

**Comment by zarevskaya** [comment]
> Very nice! Just so you know the first account can be created even if registration is disabled, I should probably clarify that:) I will add the link to the readme

Aaah, ok, sorry, I edit my article.

**Comment by C4illin** [comment]
[**@zarevskaya**](https://github.com/zarevskaya) commented on [May 29, 2024, 10:47 AM GMT+2](https://github.com/C4illin/ConvertX/issues/8#issuecomment-2136878408 "2024-05-29T08:47:18Z - Replied by Github Reply Comments"):
> > Very nice! Just so you know the first account can be created even if registration is disabled, I should probably clarify that:) I will add the link to the readme
> 
> Aaah, ok, sorry, I edit my article.
> 
> _Originally posted by @zarevskaya in https://github.com/C4illin/ConvertX/issues/8#issuecomment-2136878408_

No worries it doesn't hurt to enable, just extra work!

**Comment by C4illin** [comment]
I fixed it now, the only solution that worked for me was to remove user "bun" from Dockerfile, so it should work by default now

**Comment by zarevskaya** [comment]
Great job! Thank you very much! 
So I can remove the part chown 1000:1000 data/ -R of my tutorial?

Have a nice day and thanks for support!

**Comment by C4illin** [comment]
Yes it should work without that. I will keep it in the readme if somebody hasn't configured the docker group properly

**Comment by zarevskaya** [comment]
Ok!

You're welcome, with pleasure, I will follow the development closely because it is an interesting tool.

Take care about you and thanks for your wrok!
