### ISSUE TITLE
Error 500 with version 0.3.2

### ISSUE THREAD

**Issue by xavier-GitHub76** [C4illin/ConvertX#81]
Hello,
 with the upgrade to version 0.3.5, I have an Error 500 :
![image](https://github.com/user-attachments/assets/2aff7019-0677-4407-b440-9ba5f751cd26)

Logs :
![image](https://github.com/user-attachments/assets/3ca41e2b-bc93-41ba-8b7c-5aa0f3ce1f2b)

Monitoring (uptime-kuma) : 
![image](https://github.com/user-attachments/assets/a26e053c-136d-4262-9a56-5d51bd61c3f4)
![image](https://github.com/user-attachments/assets/1139dbef-7463-4aaa-bed3-c7c85b6ac268)

Best regards

**Comment by C4illin** [comment]
Could you test the main image? main instead of latest

**Comment by xavier-GitHub76** [comment]
I already use main.

**Comment by C4illin** [comment]
Thans for the great bug report!
