### ISSUE TITLE
Impossible to login without HTTPS

### ISSUE THREAD

**Issue by zarevskaya** [C4illin/ConvertX#9]
Hello :)

I linked a domain to your application and it works. But if I want to use it locally with the ip:port, I can't connect. 

Is this a desire on your part? Or it's possible to use it in local without HTTPS?

Have a nice day!

**Comment by C4illin** [comment]
Hello!

It is not desired, but untested.

I tested it now and I can go to the page but not log in. The auth token is set to secure so will add a environment variable to fix it.

**Comment by zarevskaya** [comment]
Same observation as me. :)

Thanks for the answer.

**Comment by C4illin** [comment]
set HTTP_ALLOWED to true and it will work. That does leave you vurnable to a man in the middle attack.

**Comment by zarevskaya** [comment]
I am well aware of it, but it was mainly to understand. Thank you very much.

**Comment by C4illin** [comment]
Thank you for reporting it

**Comment by zarevskaya** [comment]
With pleasure!
I'm publishing the article tonight at midnight. 

Thanks for all ;)
