### ISSUE TITLE
Failing to convert video files to MPEG

### ISSUE THREAD

**Issue by paintballkev812** [C4illin/ConvertX#92]
Attempted to use this tool to convert mp4 to mpeg (and mpeg2video) formats. It appears there is an issue when trying to convert to mpeg based formats. I also attempted to convert an mpeg to mpeg2video format with the same results. The log shows `[0m[31mFailed to convert ./data/uploads/1/6/1.mp4 from mp4 to mjpeg using ffmpeg. error: Error: Command failed: ffmpeg -i "./data/uploads/1/6/1.mp4" "./data/output/1/6/1.mjpeg"`

I was able to convert a mpeg to mp4 format successfully, so it seems the issue is converting to mpeg.

Running the main branch, pulled today.

**Comment by C4illin** [comment]
Choose .mpg if you want mpeg. Will look more into mjpeg seems like it need a container

**Comment by C4illin** [comment]
Should probably clean up among the ffmpeg formats and make sure all work
